#!/bin/bash
# One-time setup: grants passwordless sudo for ONLY the exact command that
# install-latest.sh uses to install this app's .deb — nothing else. No password
# is stored anywhere; sudo simply skips the prompt for that one narrow command.
#
# Run once (it asks for your password to write the rule):
#   ./setup-autoupdate-sudoers.sh
#
# Undo later with:  sudo rm /etc/sudoers.d/ledger-update
set -e

cd "$(dirname "$0")"
ROOT="$(pwd)"
USER_NAME="$(id -un)"
DEB="$ROOT/.deb-cache/latest.deb"   # must match install-latest.sh exactly
DEST="/etc/sudoers.d/ledger-update"

RULE="$USER_NAME ALL=(root) NOPASSWD: /usr/bin/apt-get install -y $DEB"

TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT
{
  echo "# Auto-generated by setup-autoupdate-sudoers.sh — lets install-latest.sh"
  echo "# install the Household Ledger .deb unattended. Scoped to this one file."
  echo "$RULE"
} > "$TMP"

echo "About to install this sudoers rule (needs your password once):"
echo
echo "    $RULE"
echo
echo "It permits ONLY installing $DEB — no other privilege."
read -r -p "Proceed? [y/N] " ans
case "$ans" in
  y|Y) ;;
  *) echo "Aborted."; exit 1 ;;
esac

# Install as root-owned 0440, then validate the whole sudoers config; back out
# if anything is wrong so a bad file can never lock you out of sudo.
sudo install -m 0440 -o root -g root "$TMP" "$DEST"
if sudo visudo -c >/dev/null; then
  echo "Installed $DEST and validated. install-latest.sh will now run unattended."
else
  echo "sudoers validation FAILED — removing the rule." >&2
  sudo rm -f "$DEST"
  exit 1
fi
